version: "3.8"
services:
  trailer_calendar:
    build: .
    container_name: trailer-calendar
    ports:
      - "8080:8080"
    environment:
      - ACCESS_CODE=${ACCESS_CODE}
      - MONTHS_AHEAD=${MONTHS_AHEAD-12}
    volumes:
      - data:/app/data
    restart: unless-stopped
volumes:
  data:
